sb = new imports.suggestionbuilder.SuggestionBuilder();
print("init sb");
function testfunc(a){
	k =  JSON.stringify(sb.suggest(a).words);
	return k;
}

function recvlist(a){
	return sb.suggest(a).words;
}

function word_committed(word, candidate){
	print("requested to commit " + word + ":" + candidate);
	sb.stringCommitted(word, candidate);
}
test = 0 ;
if (test == 1) {
stime = Date.now();
testfunc("K")
testfunc("Kh")
testfunc("Khe")
testfunc("Khey")
testfunc("Kheye")
testfunc("Kheyec")
testfunc("Kheyech")
testfunc("Kheyechi")
//------
testfunc("t")
testfunc("th")
testfunc("tha")
testfunc("thak")
testfunc("thakl")
testfunc("thakle")
testfunc("thakleo")
//------
testfunc("e")
testfunc("em")
testfunc("emn")
testfunc("emne")
//------
testfunc("n")
testfunc("na")
//------
testfunc("d")
testfunc("di")
testfunc("diy")
testfunc("diya")
//------
testfunc("B")
testfunc("Ba")
testfunc("Bar")
testfunc("Bari")
//------
testfunc("J")
testfunc("Jo")
testfunc("Jon")
testfunc("Jonn")
testfunc("Jonno")
//------
testfunc("G")
testfunc("Go")
testfunc("Gol")
testfunc("Gola")
testfunc("Golay")
//------
testfunc("g")
testfunc("gy")
testfunc("gya")
testfunc("gyac")
testfunc("gyach")
testfunc("gyache")
//------
testfunc("C")
testfunc("Ch")
testfunc("Chi")
testfunc("Chil")
testfunc("Chila")
testfunc("Chilam")
//------
testfunc("o")
//------
testfunc("i")
testfunc("in")
testfunc("inv")
testfunc("inva")
testfunc("inval")
testfunc("invali")
testfunc("invalid")
//------
testfunc("j")
testfunc("jo")
testfunc("jon")
testfunc("jono")
testfunc("jonos")
testfunc("jonose")
testfunc("jonoseb")
testfunc("jonoseba")
//------
testfunc("p")
testfunc("pa")
testfunc("pai")
testfunc("pais")
testfunc("paisi")
//------
testfunc("k")
testfunc("ko")
testfunc("kor")
testfunc("kors")
testfunc("korse")
testfunc("korsen")
//------
testfunc("P")
testfunc("Po")
testfunc("Pon")
testfunc("Pond")
testfunc("Pondi")
testfunc("Pondit")
//------
testfunc("L")
testfunc("La")
testfunc("Lat")
testfunc("Lath")
testfunc("Lathi")
testfunc("Lathir")
//------
testfunc("b")
testfunc("bi")
testfunc("bil")
testfunc("bila")
testfunc("bilai")
testfunc("bilair")
//------
testfunc("G")
testfunc("Gh")
testfunc("Gho")
testfunc("Ghor")
//------
testfunc("k")
testfunc("ka")
testfunc("kas")
testfunc("kase")
//------
testfunc("d")
testfunc("de")
testfunc("der")
//------
testfunc("e")
testfunc("er")
//------
testfunc("P")
testfunc("Po")
testfunc("Por")
testfunc("Pore")
testfunc("Porec")
testfunc("Porech")
testfunc("Porechi")
testfunc("Porechii")
//------
testfunc("g")
testfunc("gu")
testfunc("gul")
testfunc("gulo")
//------
testfunc("j")
testfunc("ja")
testfunc("jay")
testfunc("jayg")
testfunc("jayga")
testfunc("jaygay")
//------
testfunc("s")
testfunc("su")
testfunc("sur")
testfunc("suru")
//------
testfunc("e")
testfunc("es")
testfunc("eso")
testfunc("esob")
//------
testfunc("j")
testfunc("ja")
testfunc("jan")
testfunc("jani")
//------
testfunc("f")
testfunc("fi")
testfunc("fir")
testfunc("firm")
testfunc("firmw")
testfunc("firmwa")
testfunc("firmwar")
testfunc("firmware")
//------
testfunc("a")
testfunc("as")
testfunc("ase")
//------
testfunc("a")
testfunc("ap")
testfunc("apn")
testfunc("apna")
testfunc("apnar")
//------
testfunc("D")
testfunc("Do")
testfunc("Dor")
testfunc("Dori")
testfunc("Dorii")
//------
testfunc("h")
testfunc("ho")
testfunc("hoy")
testfunc("hoye")
//------
testfunc("p")
testfunc("pa")
testfunc("pab")
testfunc("pabe")
testfunc("paben")
//------
testfunc("C")
testfunc("Ch")
testfunc("Cha")
testfunc("Chal")
testfunc("Chala")
testfunc("Chalak")
//------
testfunc("a")
testfunc("ac")
testfunc("ach")
testfunc("ache")
//------
testfunc("M")
testfunc("Mo")
testfunc("Mon")
testfunc("Monc")
testfunc("Monch")
testfunc("Moncho")
//------
testfunc("m")
testfunc("mo")
testfunc("mod")
testfunc("mode")
testfunc("modem")
//------
testfunc("n")
testfunc("na")
//------
testfunc("n")
testfunc("na")
//------
testfunc("i")
testfunc("id")
testfunc("ide")
testfunc("idea")
//------
testfunc("L")
testfunc("Li")
testfunc("Lin")
testfunc("Link")
//------
testfunc("d")
testfunc("dh")
testfunc("dhu")
testfunc("dhuk")
testfunc("dhukl")
testfunc("dhukle")
//------

ctime = (Date.now()) - stime 
print("Time: " + ctime);
}
